Header header                    # 
int32 status                     # status message
int32 error                      # error message
float32 sound_speed              # acoustic sound speed in water
float64 temperature              # environment temperature
float64 pressure                 # external pressure
float64 altimeter_distance       # distance to surface/seafloor
uint32 altimeter_quality         # measurement valid